FROM python:3.11-slim

# Install system dependencies for psycopg2
RUN apt-get update && apt-get install -y libpq-dev

# Continue with the usual setup
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["python", "bot.py"]
